name: Deploy to Development Env

on:
  push:
    branches: [ development ]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
