name: Deploy to Development Env

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  run_deployment:
    runs-on: ubuntu-latest
    name: deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
      - name: Install outside dependencies
        run: ls -a
